### ISSUE TITLE
ACE libraries, .zip packaging, distribution via known addon sites.

### ISSUE THREAD

**Issue by b-morgan** [MChambers1992/CopyPasta2#1]
First, thank you for keeping this addon alive!

What have you changed in the ACE libraries? Hopefully you are aware of how the ACE libraries load into memory as WoW loads addons. After all addons are loaded, only the most up-to-date version of each ACE library remains in memory and all addons will use that copy. 

I would like to see a .zip package with the folder structure similar to almost all the other addons. I'd also like to see this addon distributed via the well known addon sites like Curse (CurseForge), and/or WOWInterface.

I use CurseForge for the addons I maintain and its package manager handles the inclusion of the latest ACE libraries. There are alternative package managers available as well.

**Comment by b-morgan** [comment]
I see you are distributing through Tukui so my request for distribution from a known site is met (even though I've never used Tukui).

**Comment by MChambers1992** [comment]
My understanding of it is that Curse is going the way of the dodo in the near future so I thought Tukui was a safer option for longevity but if there is enough demand I'm happy to put it elsewhere.

I'm not too familiar with ACE this is my first venture into addon development, I'm happy to change the structure to be more consistent with other popular addons. I'll be updating the libs to the latest versions in the next update (sometime today/tomorrow). Which would you recommend as an example of good file structure? 

Nothing is changed in ACE outside of this https://github.com/MChambers1992/CopyPasta2/blob/develop/core.lua#L646

EDIT: Just added the addon zip file to the repo now, this is the same version as the zip that is currently on Tukui.

**Comment by MChambers1992** [comment]
These issues mentioned should all be resolved now as of the last 2 commits. Let me know if there are any other issues or if this one isn't properly resolved, otherwise I'll close this one.

**Comment by b-morgan** [comment]
The link you posted above is a 404 for me.

As long as the ACE libraries you distribute with your addon are the same as those officially distributed through the official channels, we are good and you can close this issue. The ACE maintainers are pretty good at making sure the libraries are up-to-date with any changes the WoW developers throw at us.

Twitch, Curse, CurseForge are under some sort of cloud and I agree that it currently may not be the best home for an addon. I am the current maintainer/author of Skillet for retail WoW and Skillet-Classic for classic WoW. While both repositories are currently on CurseForge and I use their package manager, there are alternative package managers available. I also upload my packaged .zip files to the [WoWInterface](https://www.wowinterface.com/community.php) site and I find their forums (and their members) are very knowledgeable and helpful (and responsive) with addon related questions / information.

**Comment by MChambers1992** [comment]
I'll look into WoWInterface as it could be another good option to put the addon on. They are the official distributions of all the shared libraries, updated to the latest versions. I'll close the issue now but please feel free to open another with any other comments if you have any. Thanks!
