### ISSUE TITLE
Not an issue, just a thank you <3

### ISSUE THREAD

**Issue by KingDeVeteran** [MChambers1992/CopyPasta2#11]
Sorry for abusing the Issues tab, but, didn't know where else to put this :)

Thank you veeery much for uploading your addon to CurseForge :) from my entire library of addons, only yours and an older one, Covenant Mission Helper (which is only on Wago) were the only ones that were missing :)

Hope you're okay and cya in War Within ^_^

Feel free to close this at your own discretion and sorry again for opening an "Issue" thread :)

**Comment by MChambers1992** [comment]
Really appreciate this, thank you!
