### ISSUE TITLE
GetAddOnMetadata API Deprecated

### ISSUE THREAD

**Issue by tfmonk** [MChambers1992/CopyPasta2#14]
the GetAddOnMetadata API is Deprecated and has been moved to the C_AddOns namespace current works on live but as of 11.0.0.2 (TWW Launch) the addon will fail to work

https://github.com/Gethe/wow-ui-source/blob/7547929cf58cc69525bfe193a5444e7acb2646df/Interface/AddOns/Blizzard_Deprecated/Deprecated_10_1_0.lua#L11

All occurrences of **GetAddOnMetadata** need to be replaced with  **C_AddOns.GetAddOnMetadata**

**Comment by MChambers1992** [comment]
Thanks, I will get this fixed as soon as possible.

**Comment by MChambers1992** [comment]
Fixed in https://github.com/MChambers1992/CopyPasta2/pull/15. Thank you for assisting.
