### ISSUE TITLE
Blocked by Blizzard Ui

### ISSUE THREAD

**Issue by BanRevenant** [MChambers1992/CopyPasta2#5]
When ever trying to use /gpromote in a macro it says that the addon was blocked because of an action protected by the Blizzard UI

**Comment by MChambers1992** [comment]
Are you sure this action is specifically related to this addon? That behaviour shouldn't be impacted

**Comment by MChambers1992** [comment]
Have confirmed that this isn't a bug with this addon and is rather a bug with your specific addon set. Closing the issue.
