### ISSUE TITLE
missing release blocks 'URL' importers like WowUp

### ISSUE THREAD

**Issue by bish0polis** [MChambers1992/CopyPasta2#6]
I think WowUp is looking for a release URL to pull a zipball from.  I think it's not seeing one, and then bailing.  Consider publishing a release?

**Comment by MChambers1992** [comment]
I don't think this is an issue, the reason that WoWUp wasn't pulling in new zips is because it hadn't been updated.

**Comment by bish0polis** [comment]
> it hadn't been updated.

Which:  the add-on or wowup?

Either way, the new WowUp still hates grabbing this add-on from the github project, so SOME crutch is missing.
