### ISSUE TITLE
Tukui site took down 3rd party addon :(

### ISSUE THREAD

**Issue by KingDeVeteran** [MChambers1992/CopyPasta2#8]
So, just realized that I can't update your addon through the Tukui app :| which is sad...

I would just like to know if you're gonna continue updating the  addon here (thus so I can change from Tukui app, now obselete, to WoWUp) or if you're gonna upload your addon to CurseForge :)

Thanks for your commitment in keeping this lovely, yet old and indispensable addon alive <3

EDIT: Tried now to get the addon through WoWUp, but it doesn't find it, sadly :|

**Comment by wduda** [comment]
The solution would be to create a GitHub action that would package new versions of the plugin into a GitHub release. That would be enough so WoWUp can download straight from here.

**Comment by MChambers1992** [comment]
Hey guys as mentioned in #9 I will look to figure this out to avoid issues with updates
